name: Publish pods to CocoaPods

on:
  workflow_dispatch:

jobs:
  release:
    name: Create release
    runs-on: macos-latest

    steps:
    - name: Checkout release repository
      uses: actions/checkout@v4
      with:
        ref: master
        path: source

    - name: Checkout sdk automation scripts
      uses: actions/checkout@v4
      with:
        repository: moengage/sdk-automation-scripts
        path: sdk-automation-scripts
        token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}

    - name: Setup iOS
      uses: ./sdk-automation-scripts/actions/ios-action-setup
      env:
        SDK_BOT_ACCESS_TOKEN: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}

    - name: Publish pods
      run: ${{ github.workspace }}/sdk-automation-scripts/scripts/release/ios/pod_push.rb
      working-directory: source
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
